feat list events table ETI-99
mecantronic/etitango-front pull request #65
Opened 2024-04-05 16:28 UTC by LRAlvaro

## *Brief Summary*

Feature list table of events added mobile and desktop

## *Type of change:*

- [x]  *Feature*
- [ ]  *Bugfix*
- [x]  *Refactor*
- [ ]  *Hotfix*
- [ ]  *Breaking change ()*
- [ ]  *Documentation*

2024-04-05 20:39 UTC, ortega-pablo requested changes
Chicos! Les dejo algunos issues visuales que fuimos encontrando:

- Centrar el mensaje de "No hay evento disponibles" y colocar la palabra disponible en lugar de creados.
  ![Captura de pantalla 2024-04-05 141408](https://github.com/mecantronic/etitango-front/assets/87724507/73eb5b83-f693-4860-9dfd-fd525060b389)

- Al crear un nuevo evento, la web me redirige a la vista de edición y aparece seleccionado el evento que acabamos de crear. El problema es que no cambia la selección del menú (la sidebar)
  ![Captura de pantalla 2024-04-05 141501](https://github.com/mecantronic/etitango-front/assets/87724507/f98083f7-b2d6-48ae-abdc-5fa3eabcc350)

- En la vista desktop de la lista de eventos necesitamos corregir tres cosas:
  - No debería aparecel las barras de desplazamiento al reducir el tamaño de la pantalla (a medida que voy cambiando la pantalla de formato desktop a mobile)
  - Las columnas deberían verse todo el tiempo completas porque el checkbox desaparece si existe el scroll. Esto podemos solucionarlo colocando a las columnas la propiedad flex en lugar de width. Por ejemplo podría ser nombre con flex:1 y email con flex:3
  - Hay una fila extra vacía al final que deberíamos sacar
  
  ![Captura de pantalla 2024-04-05 164857](https://github.com/mecantronic/etitango-front/assets/87724507/f8097a1d-1cb4-48d6-89cd-07efd401e2c3)
 ![image](https://github.com/mecantronic/etitango-front/assets/87724507/782b7250-ff55-40a5-be38-959258cbbfea)


- En la vista mobile de la tabla de eventos tenemos que solucionar:
  - Los scroll que aparecen en la vista (no debería suceder)
  - El tamaño de los elementos (po ejemplo el header está muy angosto)
  - La cantidad de elementos a renderizar (se deben renderizar 5 o 6 elementos, pero no 4
  
  ![Captura de pantalla 2024-04-05 164918](https://github.com/mecantronic/etitango-front/assets/87724507/a10eb310-3105-4fce-93b8-d35614b051a7)

- Respecto al modal de eliminar, debemos respetar el tamaño del mismo (actualmente tiene mucha altura y poco ancho)
  ![Captura de pantalla 2024-04-05 165102](https://github.com/mecantronic/etitango-front/assets/87724507/2bd1fd2a-de7d-4d64-b8d8-718895c0e60e)

2024-04-05 20:39 UTC, ortega-pablo commented on src/components/events/ETIModalDeleteEvent.tsx
> +        <Box sx={{ borderBottom: '1px solid #E0E0E0', width: '100%' }}></Box>
Importar color desde el theme

2024-04-05 20:39 UTC, ortega-pablo commented on src/components/events/ETIModalDeleteEvent.tsx
> +        {!isMobile ? (
En lugar de utilizar un operador ternario y colocar un null al final simplemente podemos utilizar el operador && para sólo realizar una acción si la propiedad es true

2024-04-05 20:39 UTC, ortega-pablo commented on src/components/events/ETIModalDeleteEvent.tsx
> +                border: '1px solid #9E9E9E',
Importar color desde el theme

2024-04-05 20:39 UTC, ortega-pablo commented on src/components/events/ETIModalDeleteEvent.tsx
> +                color: 'white',
Importar color desde el theme

2024-04-05 20:39 UTC, ortega-pablo commented on src/modules/superAdmin/events/EventsList.tsx
> +  const [eventData, setEventData] = useState<EtiEvent | null>(null);
Variable no utilizada, corregir problema

2024-04-05 20:39 UTC, ortega-pablo commented on src/modules/superAdmin/events/EventsList.tsx
>        const evts = await firestoreEventHelper.getEvents();
No utilizar esta abreviatura, Dejar un nombre para la variable que sea explicativo

2024-04-05 20:39 UTC, ortega-pablo commented on src/modules/superAdmin/events/eventsListTable.tsx
> +      width: 250,
Cambiar por propiedad flex para eliminar el scroll horizontal

2024-04-05 20:39 UTC, ortega-pablo commented on src/modules/superAdmin/events/eventsListTable.tsx
> +      width: 600,
Cambiar por propiedad flex para eliminar el scroll horizontal

2024-04-05 20:39 UTC, ortega-pablo commented on src/modules/superAdmin/events/eventsListTable.tsx
> +        ) : userIsSuperAdmin ? (
Utilizar && en lugar de operador ternario

2024-04-05 20:39 UTC, ortega-pablo commented on src/modules/superAdmin/events/eventsListTable.tsx
> +              ) : null}
Utilizar operador && no ternario

2024-04-08 16:16 UTC, LRAlvaro commented on src/components/events/ETIModalDeleteEvent.tsx
> +        <Box sx={{ borderBottom: '1px solid #E0E0E0', width: '100%' }}></Box>
El color no se puede importar desde el theme debido a que utiliza el estilo border y/o borderBottom y no "color".

2024-04-10 14:06 UTC, ortega-pablo commented on src/components/events/ETIModalDeleteEvent.tsx
> +        <Box sx={{ borderBottom: '1px solid #E0E0E0', width: '100%' }}></Box>
Esto sí se puede resolver incorporando el color de esta manera:

![image](https://github.com/mecantronic/etitango-front/assets/87724507/fa4fd475-b7ee-4e65-9e62-c3a6ccfb82e9)

Para que no genere el error de typescript debemos incorporar greyscale a los tipos de theme de la siguiente forma:

![image](https://github.com/mecantronic/etitango-front/assets/87724507/c2635361-d6d2-4028-8b08-e7fbf3420980)

2024-04-10 14:07 UTC, ortega-pablo commented on src/components/events/ETIModalDeleteEvent.tsx
> +                border: '1px solid #9E9E9E',
Resolver incorporando el theme

2024-04-10 14:38 UTC, ortega-pablo requested changes
El usuario administrador NO debe poder ver el botón de los 3 puntitos que habilita la opción de borrado (esto no está solucionado en mobile)
En  mobile dejar renderizados 6 elementos para que el elemento inferior quede en azul y reducir el espaciado entre las filas y el paginado
![image](https://github.com/mecantronic/etitango-front/assets/87724507/0113e55b-6bbc-4d01-bbc6-627392c0bccc)

2024-04-10 14:38 UTC, ortega-pablo commented on src/modules/superAdmin/events/EventForm.tsx
>          const idEvento = await createOrUpdateDoc('events', values, id === 'new' ? undefined : idV);
Colocar nombre de variable en inglés

2024-04-10 14:38 UTC, ortega-pablo commented on src/modules/superAdmin/events/eventsListTable.tsx
> +                  border: '2px solid #A82548',
Colocar color desde el theme

2024-04-10 14:38 UTC, ortega-pablo commented on src/components/events/ETIModalDeleteEvent.tsx
Para corregir el error 
![image](https://github.com/mecantronic/etitango-front/assets/87724507/2bd0d13f-f2d7-44fe-a403-ea4cd6dd483b)
Podemos envolver al elemento completo con React.forwardRef

2024-04-10 19:20 UTC, ortega-pablo requested changes

2024-04-10 19:20 UTC, ortega-pablo commented on src/components/events/ETIModalDeleteEvent.tsx
Este componente genera el siguiente warning:
![image](https://github.com/mecantronic/etitango-front/assets/87724507/50eb4f02-7985-4587-87b7-d3457fee3929)

Esto se soluciona incorporando un nombre de display al mismo de la siguiente manera:
![image](https://github.com/mecantronic/etitango-front/assets/87724507/c6c4f377-ecbd-4188-ad8e-07c18ca4466b)

2024-04-10 21:42 UTC, merged